# ===============================
# CONFIGURAZIONE GENERALE APP
# ===============================

spring.application.name=demo
# Nome dell'applicazione Spring Boot.
# Per identificazione (log, monitoring, ecc.)

server.port=8081
# Porta su cui gira il server backend.
# http://localhost:8081


# ===============================
# CONFIGURAZIONE DATABASE
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/ticketing_itconsulting?createDatabaseIfNotExist=true
# URL di connessione al database MySQL:
# - localhost → database sulla stessa macchina
# - 3306 → porta standard MySQL
# - ticketing_itconsulting → nome database
# - createDatabaseIfNotExist=true → crea DB automaticamente se non esiste

spring.datasource.username=root
# Username per accesso al database

spring.datasource.password=root
# Password per accesso al database (di default)

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Driver JDBC utilizzato per comunicare con MySQL


# ===============================
# CONFIGURAZIONE JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
# Strategia di gestione schema DB:
# - update → aggiorna automaticamente le tabelle in base alle entity
# utile in sviluppo, ma NON consigliato in produzione

spring.jpa.show-sql=true
# Mostra tutte le query SQL eseguite in console/log
# Per debug